-- Drop existing tables to ensure the script runs cleanly every time
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE predictions CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE app_details CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP SEQUENCE USER_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- Ignore errors if tables or sequence don't exist
END;
/

-- Create users table with additional fields
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    weight NUMBER(10, 2), -- New field for weight
    height NUMBER(10, 2), -- New field for height
    training_habits VARCHAR2(500) -- New field for training habits
);

-- Create predictions table
CREATE TABLE predictions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER, -- Foreign key to users table
    prediction_data CLOB,
    prediction_result TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Create app_details table
CREATE TABLE app_details (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_name VARCHAR2(255),
    version VARCHAR2(50),
    release_date TIMESTAMP
);

-- Create sequence for users (if needed)
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;

-- Commit the changes
COMMIT;
